sudo: required
services:
 - docker

before_install:
 - docker build -t mbeff/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run mbeff/react-test npm test -- --coverage

after_success:
 - docker build -t melissabeff/multi-client ./client
 - docker build -t melissabeff/multi-nginx ./nginx
 - docker build -t melissabeff/multi-server ./server
 - docker build -t melissabeff/multi-worker ./worker
#log in to the docker CLI
 - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
#take those eimages und push them to dockerhub
 - docker push melissabeff/multi-client
 - docker push melissabeff/multi-nginx
 - docker push melissabeff/multi-server
 - docker push melissabeff/multi-worker
 
deploy:
 provider: elasticbeanstalk
 region: us-east-2
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-us-east-2-856871384121
 bucket_path:
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
   secure: $AWS_SECRET_KEY
