sudo: required
services:
 - docker

before_install:
 - docker build -t mbeff/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run mbeff/react-test npm test -- --coverage

after_success:
 - docker build -t mbeff/multi-client ./client
 - docker build -t mbeff/multi-nginx ./nginx
 - docker build -t mbeff/multi-server ./server
 - docker build -t mbeff/multi-worker ./worker
#log in to the docker CLI
 - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
#take thos eimages und push them to dockerhub
 - docker push mbeff/multi-client
 - docker push mbeff/multi-nginx
 - docker push mbeff/multi-server
 - docker push mbeff/multi-worker
 
